# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_tweetsort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetsort',
            name='twt_count',
        ),
        migrations.AddField(
            model_name='tweetsort',
            name='twt_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
