# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_tweetcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetcount',
            old_name='twt_id',
            new_name='count',
        ),
    ]
